name: Bug Report
description: Report a bug you came across
title: "[Bug]: "
labels: [bug]
assignees: "Doglover1219"

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
  - type: input
    id: title
    attributes:
      label: Short Title
      description: A short title for the bug
      placeholder: e.g. "Image Resolution is bad"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What’s the problem?
      description: A more detailed description of the bug
      placeholder: e.g. "This feature isn't working"
    validations:
      required: true